/* tslint:disable */
/* eslint-disable */
/**
 * WsApi
 * Galileo Websocket api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SendChatMessageRequestContent
 */
export interface SendChatMessageRequestContent {
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageRequestContent
     */
    chatId: string;
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageRequestContent
     */
    tmpMessageId: string;
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageRequestContent
     */
    question: string;

}


/**
 * Check if a given object implements the SendChatMessageRequestContent interface.
 */
export function instanceOfSendChatMessageRequestContent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chatId" in value;
    isInstance = isInstance && "tmpMessageId" in value;
    isInstance = isInstance && "question" in value;

    return isInstance;
}

export function SendChatMessageRequestContentFromJSON(json: any): SendChatMessageRequestContent {
    return SendChatMessageRequestContentFromJSONTyped(json, false);
}

export function SendChatMessageRequestContentFromJSONTyped(json: any, _ignoreDiscriminator: boolean): SendChatMessageRequestContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chatId': json['chatId'],
        'tmpMessageId': json['tmpMessageId'],
        'question': json['question'],
    };
}

export function SendChatMessageRequestContentToJSON(value?: SendChatMessageRequestContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chatId': value.chatId,
        'tmpMessageId': value.tmpMessageId,
        'question': value.question,
    };
}

